### ISSUE TITLE
Tool rack crash

### ISSUE THREAD

**Issue by yujukitten** [TeamMD5/Reliquia#11]
Hi, 

I have been building a new server pack and all my local tests were great when I went to test it locally with the server save. I received this crash. (which might be a duplicate of issue#9 i think) I thought I would post it separately in case I am wrong. Awesome work *^^* 
[latest.txt](https://github.com/TeamMD5/Reliquia/files/840365/latest.txt)

**Comment by KitsuneAlex** [comment]
Reliquia is currently being rewritten so this issue is not gonna be fixed in Reliquia 1, thanks for the report tho, have a nice day =)
