### ISSUE TITLE
Can't Place Hoes in tool rack

### ISSUE THREAD

**Issue by BrisingrAerowing** [TeamMD5/Reliquia#3]
As per title. Hoes cannot be placed in the tool rack.

Version 0.0.6
Minecraft 1.10.2
Forge 12.18.3.2185

**Comment by KitsuneAlex** [comment]
Reliquia 0.0.7 is on it's way already so no long waiting till that is fixed as well, thanks for the info ! =)

**Comment by BrisingrAerowing** [comment]
Thanks. This a very cool mod.

**Comment by KitsuneAlex** [comment]
thank you =)
