### ISSUE TITLE
Can't put tinkers construct tools into toolrack

### ISSUE THREAD

**Issue by thiagobaisch** [TeamMD5/Reliquia#8]
Right now, playing on skyfactory 3, the relíquia toolrack does not permit tinkers tools to be put on

**Comment by KitsuneAlex** [comment]
yes the toolracks are a little buggy at the moment, ill take care of that in the next update =)

**Comment by Artanis** [comment]
Maybe related, but the plinths don't appear to take Tinkers' broadsword (vanilla Sword equivalent).

**Comment by KitsuneAlex** [comment]
i am currently working on Reliquia 2, for updates check my twitter http://twitter.com/KitsuneAlexx/ - also these things are fixed in 2.0.0, i now have proper packet handling and compat modules =)
